### ISSUE TITLE
Implement Redis with Packet post

### ISSUE THREAD

**Issue by c-lawrence** [cs481-ekh/f22-gneiss#135]
As a user, I want to create a post request through Redis, so I can generate packets.

tasks:
- [ ] #155 

Definition of Done:
- [ ] Figure out what I'm doing

**Comment by Phillipnewell** [comment]
1 hour - Finding workable client
1 hour - converting to kotlin
few hours - debugging docker and maven building
2 hours - Using Postman and confirming PacketPost
