### ISSUE TITLE
Add a create account page

### ISSUE THREAD

**Issue by TheodoreRamey** [cs481-ekh/f22-gneiss#18]
References #8 

Add a create account form that is linked to the login page, allowing for a Firstname, Lastname, E-mail, and a properly-formatted password. This should allow the user to create a new account and allow their information to be linked up to the Create Account REST endpoint.

- [x] #50 
- [x] #34
- [x] #51
- [x] #64

Definition of Done:
- [x] UI page is able to be viewed in the local dev environment.
- [x] User is able to create valid accounts.
- [x] User is unable to create accounts that violate the parameters of an information field.
- [x] Information on the new user account is passed somewhere which can be integrated into the backend.
- [x] All unit tests are passing.

**Comment by c-lawrence** [comment]
Basically done, just waiting for the backend element to be finished so I can connect it.

**Comment by c-lawrence** [comment]
Worklog (Sprint 3): See #64 and associated branch.

**Comment by c-lawrence** [comment]
#64 is resolved, DOD fulfilled, Story closed.
