### ISSUE TITLE
Front-end Invoice Step Component

### ISSUE THREAD

**Issue by jacksontheel** [cs481-ekh/f22-gneiss#85]
Given an Invoice stored locally, when the User selects that Invoice in the front-end UI, the Invoice is uploaded to the final output as a component.

This will be the first step in the Stepper component, to parallel its placement in the final packet. This page will have an "Upload PDF" button, and a "Save" button.

- [x] #101 
- [x] #102
- [ ] #104
- [x] #103

Definition of Done:

- [x] New UI elements built
- [x] Stepper works as expected
- [x] Able to upload Invoices
- [ ] Able to Save
- [x] All Unit tests passing

**Comment by c-lawrence** [comment]
UI elements working on-branch, need to connect to the backend and build remaining tests.

**Comment by c-lawrence** [comment]
Worklog:

10/1: Setup stepper element & basic functionality ~2 hours #101
10/2: Built initial file selection element ~ 1 hour #101, #102
10/6: Encountered error with implementing Axios ~ 2 hours #101, #102
10/7: Researched & fixed issue ~45 minutes #102
10/10: Standardized buttons with Approval step, setup unit tests, finalized elements. ~1.5 hours #101, #102, #103
