### ISSUE TITLE
Packet POST

### ISSUE THREAD

**Issue by jacksontheel** [cs481-ekh/f22-gneiss#89]
As a user, I want to be able to make changes to the packet, so that I can get work done.

## Definition of Done
- [x] Have code work through POSTMAN
- [x] Takes all data from the packet
- [x] Receives response

## Tasks
- [x] #115

**Comment by Phillipnewell** [comment]
Downloading and learning Postman ~ 2 hours
Pair programmed with Jackson ~ 1 hour
