### ISSUE TITLE
CreatePDF endpoint

### ISSUE THREAD

**Issue by jacksontheel** [cs481-ekh/f22-gneiss#91]
As a user, I want to be able to upload a PDF (invoice), so that it can be included in the final packet. 

## Definition of Done
- [ ] Able to upload a PDF and return a filename.
- [ ] The filename returned corresponds to where the file exists on some server.

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by TheodoreRamey** [comment]
Didn't get to work on this during Sprint 2 due to time management issues.

**Comment by TheodoreRamey** [comment]
Redundant as Jackson created a similar story and implemented it.
