### ISSUE TITLE
Get Pipeline passing

### ISSUE THREAD

**Issue by jacksontheel** [cs481-ekh/f22-gneiss#97]
As a developer, I want CI to be passed, so we can keep building our web app

## Definition of Done
- [ ] Ability to manually push github workflow dispatch
- [ ] Fix ktlinter
- [ ] docker frontend
- [ ] other errors in workflow events

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by Phillipnewell** [comment]
Rounding down the problems by commenting out some code ~ 1 hour
Learning github actions ~ 1 hour
Configured Github actions with workflow dispatch ~ 3 hours
Finding out how to use ktlint and trying all the different ways to run it ~ 2 hours
Having someone just run the command on a Mac ~ 0.01 hours
